[2023-11-28 00:52:27,447] => Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
[2023-11-28 00:52:27,448] => Exception traceback:
Traceback (most recent call last):
  File "C:\Users\serv\PycharmProjects\SecretSanta\venv\lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\serv\PycharmProjects\SecretSanta\venv\lib\site-packages\telebot\util.py", line 147, in raise_exceptions
    raise self.exception_info
  File "C:\Users\serv\PycharmProjects\SecretSanta\venv\lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "C:\Users\serv\PycharmProjects\SecretSanta\venv\lib\site-packages\telebot\__init__.py", line 6801, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "C:\Users\serv\PycharmProjects\SecretSanta\SecretSanta\app.py", line 173, in sec
    Notifier().select_santa()
  File "C:\Users\serv\PycharmProjects\SecretSanta\SecretSanta\app.py", line 152, in select_santa
    chats[santa_id].add_message(Message(TXT_SANTA),'santa')
  File "C:\Users\serv\PycharmProjects\SecretSanta\SecretSanta\app.py", line 77, in add_message
    msg.send_message(self.__id)
  File "C:\Users\serv\PycharmProjects\SecretSanta\SecretSanta\app.py", line 31, in send_message
    self.__msg = bot.send_message(chat_id=chat_id, text=self.text, reply_markup=self.keyboard)
  File "C:\Users\serv\PycharmProjects\SecretSanta\venv\lib\site-packages\telebot\__init__.py", line 1549, in send_message
    apihelper.send_message(
  File "C:\Users\serv\PycharmProjects\SecretSanta\venv\lib\site-packages\telebot\apihelper.py", line 264, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "C:\Users\serv\PycharmProjects\SecretSanta\venv\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\serv\PycharmProjects\SecretSanta\venv\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

